<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.jdom</groupId>
    <artifactId>jdom-parent</artifactId>
    <packaging>pom</packaging>

    <name>JDOM Parent</name>
    <version>3.1</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <pluginRepositories>
        <pluginRepository>
            <id>consulo</id>
            <url>https://maven.consulo.dev/repository/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>java9-force</id>
            <activation>
                <property>
                    <name>force.java9.compilation</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
                <maven.compiler.source>9</maven.compiler.source>
                <maven.compiler.target>9</maven.compiler.target>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>consulo.maven</groupId>
                            <artifactId>java9-maven-plugin</artifactId>
                            <version>1.2</version>
                            <extensions>true</extensions>
                            <executions>
                                <execution>
                                    <id>java9</id>
                                    <phase>process-sources</phase>
                                    <goals>
                                        <goal>generate-source-module-info</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>

        <profile>
            <id>java9-force-unset</id>
            <activation>
                <property>
                    <name>!force.java9.compilation</name>
                </property>
            </activation>
            <properties>
                <maven.compiler.source>8</maven.compiler.source>
                <maven.compiler.target>8</maven.compiler.target>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>consulo.maven</groupId>
                            <artifactId>java9-maven-plugin</artifactId>
                            <version>1.2</version>
                            <extensions>true</extensions>
                            <executions>
                                <execution>
                                    <id>pre-java9</id>
                                    <phase>process-classes</phase>
                                    <goals>
                                        <goal>generate-binary-module-info-nocheck</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

    <modules>
        <module>jdom-core</module>
        <module>jdom-sax</module>
        <module>jdom-core-test</module>
        <module>jdom-contrib</module>
        <module>jdom-xpath-jaxen</module>
        <module>jdom-xpath-java5</module>
        <module>jdom-xpath-java5-test</module>
        <module>jdom-xpath-xalan</module>
        <module>jdom-to-dom</module>
    </modules>
</project>