<project>
    <parent>
        <groupId>org.jdom</groupId>
        <artifactId>jdom-parent</artifactId>
        <version>3.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jdom-core-test</artifactId>
    <packaging>jar</packaging>

    <name>JDOM Core - Test Api</name>
    <version>3.1</version>
    
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jdom-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>
</project>