<project>
    <parent>
        <groupId>org.jdom</groupId>
        <artifactId>jdom-parent</artifactId>
        <version>3.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jdom-xpath-java5</artifactId>
    <packaging>jar</packaging>

    <name>JDOM XPath - Java 5 implementation</name>
    <version>3.1</version>
    
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jdom-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jdom-core-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jdom-to-dom</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>